version: 2
jobs:
  docker_build_lts:
    docker:
      - image: circleci/node
    working_directory: ~/electron-starter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Docker build with Node LTS
          command: docker build --build-arg node_version=lts .
  docker_build_8_latest:
    docker:
      - image: circleci/node
    working_directory: ~/electron-starter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Docker build with Node 8 (latest)
          command: docker build --build-arg node_version=8 .
  docker_build_9_latest:
    docker:
      - image: circleci/node
    working_directory: ~/electron-starter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Docker build with Node 9 (latest)
          command: docker build --build-arg node_version=9 .
  docker_build_10_0_0:
    docker:
      - image: circleci/node
    working_directory: ~/electron-starter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Docker build with Node 10.0.0
          command: docker build --build-arg node_version=10.0.0 .
  docker_build_10_latest:
    docker:
      - image: circleci/node
    working_directory: ~/electron-starter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Docker build with Node 10 (latest)
          command: docker build --build-arg node_version=10 .
  docker_build_11_latest:
    docker:
      - image: circleci/node
    working_directory: ~/electron-starter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Docker build with Node 11 (latest)
          command: docker build --build-arg node_version=11 .
workflows:
  version: 2
  build_and_test:
    jobs:
      - docker_build_lts
      - docker_build_8_latest
      - docker_build_9_latest
      - docker_build_10_latest
      - docker_build_11_latest
      - docker_build_10_0_0
